#!/usr/bin/env bash

apt_packages=$(cat <<EOF
neovim
tmux
git
htop
tree
wget
bash-completion@2
docker-completion
docker-compose
gcc
jq
ctags
colordiff
pgcli
nvm
fzf
curl
EOF
)

#  install OH MY ZSH
sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

sudo apt install $apt_packages
