#!/usr/bin/env bash

brew_packages=$(cat <<EOF
alacritty
neovim
moreutils
exiftool
coreutils
tmux
git
git-standup
htop
tree
wget
bash-completion@2
docker-completion
docker-compose
gcc
imagemagick
jq
ctags
colordiff
pgcli
nvm
fzf
ripgrep
nodejs
rectangle
lazygit
EOF
)

# install ohmyzsh
sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

brew install $brew_packages
