#!/usr/bin/env bash

brew_packages=$(cat <<EOF
neovim
exiftool
coreutils
git
git-standup
htop
tree
wget
gcc
jq
ctags
colordiff
pgcli
fzf
ripgrep
rectangle
lazygit
httpie
EOF
)

# install ohmyzsh
#sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# install starship
curl -sS https://starship.rs/install.sh | sh

bash < <(curl -s -S -L https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer)

brew install $brew_packages
