#!/usr/bin/env bash

#  install OH MY ZSH
sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

apt_packages=$(cat <<EOF
neovim
tmux
git
htop
tree
wget
docker-compose
gcc
jq
ctags
colordiff
pgcli
fzf
curl
zlib-devel
bzip2
bzip2-devel 
readline-devel 
sqlite 
sqlite-devel 
openssl-devel 
xz 
xz-devel 
libffi-devel 
findutils 
EOF
)


sudo dnf install $apt_packages -y
sudo dnf groupinstall "Development Tools" -y

